- common/rulesys.cpp
- common/rulesys.h
- common/ruletypes.h
- world/client.cpp
- world/clientlist.cpp
- world/zoneserver.cpp
- zone/lua_general.cpp
* Exempt zone from IP checks
* [Feature] Add Support for String-based Rules
- Add support for string-based rules.
* convert to comma-seperated list
* Forgot to convert the zone to a string
* Update lua_general.cpp
* fixed rule name
* use the local string methods instead
* I think this will work as desired without the extra condition
---------
> [Feature] Exempt a zone from IP-limit checks. (#4137)

- zone/aggro.cpp
- zone/attack.cpp
- zone/mob.cpp
- zone/spell_effects.cpp
- zone/spells.cpp
Change ration to 2x damage, and use correct item ID.
> Fix multiple issues regarding Multi-Classing

- common/inventory_profile.cpp
This will allow any function that calls _HasItem from the inventory profile to return true if the item is upgraded.
> Add upgraded item checks to _HasItem in inventory profile

- zone/client_packet.cpp
Reduce camp timer in bazaar to 5s
> Add fast camp to bazaar

- zone/effects.cpp
- zone/special_attacks.cpp
- zone/spell_effects.cpp
Checking LoS for all skill attacks and ranged attacks.
> Check LoS for all SkillAttacks

- zone/special_attacks.cpp
> Fix ranged proc

- zone/bonuses.cpp
Also looked through other potential non-stacking AA and determined no issues. Left notes.
> Made extra attack stackable (ferocity & knight's advantage)

- zone/client_process.cpp
> Fix infinite ranged double attack again because Catapultam Habeo always reverts my changes

- zone/bonuses.cpp
> Enable spell critical damage increases to stack

- zone/special_attacks.cpp
> Allow Offense Skillups while throwing and Pew pewing

- common/ruletypes.h
- zone/bonuses.cpp
>  Adds rules to apply a soft cap for additive spell crit damage. 

- zone/client_process.cpp
No rent items will no longer fade if you are a Magician ✨🧙
> Grant Magicians a stronger bond with the summoned realm

- zone/client.cpp
- zone/gm_commands/set/name.cpp
- zone/questmgr.cpp
Zone crash fixes for EQEmu changename PR
> Fix some bad argument types.

- world/clientlist.cpp
- world/clientlist.h
- world/wguild_mgr.cpp
- world/zonelist.cpp
- world/zonelist.h
- world/zoneserver.cpp
- zone/client_packet.cpp
> [Performance] Have World Send Smarter Guild Updates

- zone/client_packet.cpp
> [Performance] Reduce Adventure S2S chatter

- common/ruletypes.h
- zone/client.cpp
> [Performance] Reduce LFGuild Chatter

- common/ruletypes.h
- zone/corpse.cpp
> [Performance] Reduce CorpseOwnerOnline S2S Chatter to World

- zone/loot.cpp
> Actually fix shields and 2h in pet bag

- zone/attack.cpp
Fixes a bug where swarm pets are ignoring proc rate caps
> Fix swarm pet check for pet proc rate cap

- common/item_instance.cpp
- common/item_instance.h
- zone/client_packet.cpp
- zone/loot.cpp
> Augment slot stuff

- zone/client_packet.cpp
> Fix happy path augments

- zone/attack.cpp
Adds some debugging to try to track down mysterious pet disappearances.
> Add error logging when removing an invalid pet

- zone/loot.cpp
Reverts The-Heroes-Journey-EQEMU/Server#141
its no good and bad
> Revert "Also removes items when clearing loot items"

- zone/attack.cpp
Redo of https://github.com/The-Heroes-Journey-EQEMU/Server/pull/130 which got reverted for a Different Approach that broke pets completely or something.
> Fixes a bug where swarm pets are ignoring proc rate caps

- common/database_schema.h
- zone/attack.cpp
- zone/client.h
- zone/client_packet.cpp
- zone/client_process.cpp
- zone/common.h
- zone/gm_commands/petcmd.cpp
- zone/hate_list.cpp
- zone/mob.h
- zone/mob_ai.cpp
- zone/npc.cpp
- zone/npc.h
- zone/pets.cpp
- zone/special_attacks.cpp
- zone/spells.cpp
* Redirect owner's aggro to taunting pet
* Fix some issues with attackmode ranged
* add acct-scoped alt currency to backup set
* reworked shaman pet name generator
* fix pet rampage issues
* add /pet assist and friends
> Omnibus update

- zone/client.cpp
- zone/spell_effects.cpp
Doppelganger spell priority tweaks
> Doppelganger spell priority tweaks

- zone/client.cpp
> fix skeleton model

- zone/trading.cpp
- zone/worldserver.cpp
I have no idea how this works, got it from Neckkola.
> Fix barter transaction error

- zone/spell_effects.cpp
> adjust dot scaling again

- zone/spell_effects.cpp
> Dot Fix 2: Electric Boogaloo
