- zone/common.h
Add header to initialize value of (0) for AE Rampage.
> Fix overflow/unitialized value for AE Rampage

- common/ruletypes.h
- zone/mob.cpp
added configurable summon rules to Mobs.
`RULE_REAL(Range,MaxZSummonOffsetIndoor, 10.00, "Maximum distance on Z Axis to which a player can be summoned indoors") 
RULE_REAL(Range,MaxZSummonOffsetOutdoor, 255.00, "Maximum distance on Z Axis to which a player can be summoned outdoors")
RULE_BOOL(NPC, SummonTimerScaling, false, "Enable to allow SummonTimer to scale to the maximum value defined by Maximum Summon Timer")
RULE_INT(NPC, MaximumSummonTimerMs, 30000, "Maximum Summon Timeout for mobs to re-summon a player") RULE_INT(NPC, NPCSummonTimer, 6000, "Default Summon Timer for NPCs")`
> Add configurable summon parameters

- zone/exp.cpp
Fixes a crash bug when leveling items by killing mobs that are not green or light blue. This code does compile out of the box on Windows 11.
> Patch Leveling items zone crash

- zone/special_attacks.cpp
This removes the 1HPiercing restriction from base damage calculation for backstab weapon damage.
There's logic before this that prevents clients from backstabbing using 1HPiercing as appropriate -- it's okay to just return the weapon damage value here and let it be calculated in `RogueBackstab`
> Remove 1hpiercing restriction for calculating base backstab damage

- zone/exp.cpp
I noticed while working on my Temple of Solusek Ro quests that I wasn't getting any exp message even from quests that had exp rewards configured in the quest scripts. Then I realized I had AA exp set to max and I think I found the bug after digging in a little bit here.
I think that the change here accidentally made it so that quests would no longer reward any AA exp: https://github.com/The-Heroes-Journey-EQEMU/Server/commit/27f796cbed39d335ad896e39f3cc87631ba696a6#diff-214a50474aa7ed005ab50748415739244a24e11a411d83564ed2dcc29f16661a
`GetConLevelModifierPercent`:
https://github.com/The-Heroes-Journey-EQEMU/Server/blob/67b42322ee959ac01a7d63fd467044ddd39433c7/zone/exp.cpp#L222-L247
This returns `0` if there is no `conlevel` which there won't be if the exp is coming from a non-kill source. …
> Fixes a bug with exp rewards from quests

- zone/attack.cpp
- zone/mob.cpp
- zone/spells.cpp
…c attempts
**None of this is tested / definitely needs to go on dev server to fuck around with / probably has standard egregious typos and syntax errors but the spirit is correct.**
This changes `TrySpellProc` to enable `m_max_procs` proc effects to occur rather than `m_max_procs` proc effects to be _attempted_.
`MAX_PROCS` (and arrays) gets initialized here:
https://github.com/The-Heroes-Journey-EQEMU/Server/blob/e7470278f7f8f5e8e0c90090d9490a0271a1d628/zone/mob.h#L1677-L1681
The max proc values and arrays all get set / reset here:
https://github.com/The-Heroes-Journey-EQEMU/Server/blob/e7470278f7f8f5e8e0c90090d9490a0271a1d628/zone/mob.cpp#L297-L321
> Enable up to `RuleI(Combat, MaxProcs)` spell/AA procs rather than proc _attempts_

- zone/spells.cpp
There are certain edge cases right now which allow buffs to be added multiple times to the spell procs array (if a buff never fades).
This change prevents and protects against those edge cases by only allowing each spell to be added one time to the SpellProcs array.
> Adds a sanity check to prevent adding the same spell ID as a proc multiple times

- zone/cli/npc_handins.cpp
- zone/npc.cpp
This resolves an issue where only exact inputs where allowed during a single hand-in. This change allows for example 4 item's to be handed-in and 1 required item to be checked and met, which plucks off of the stack of handed-in items for each successful hand-in.
Below is handing in 4 of the explorer items in Bazaar
Passing test cases
```
ZoneSi |    Info    | StartFileLogs Starting File Log [logs/zone/qrg_version_0_inst_id_0_port_0_10702.log] -- [qrg] (The Surefall Glade) inst_id [0]
ZoneSi |    Info    | StopShutdownTimer Stopping zone shutdown timer -- [qrg] (The Surefall Glade) inst_id [0]
ZoneSi |    Info    | NpcHandins ---------------------------------------- -- [qrg] (The Surefall Glade) inst_id [0]
ZoneSi |    Info    | NpcHandins Done booting test zone -- [qrg] (The Surefall …
```
> [Handin] Fix successive handins

- zone/cli/npc_handins.cpp
- zone/npc.cpp
This was reported in a support thread. This is an edge case because of how the quest is written but my goal is to make all existing quests work regardless and be flexible to all the cases within reason.
**NPC** 
**Tkyar Renlin** in **freeporte**
Example quest
```lua
function event_trade(e)
local champagne = 0;
local item_lib = require("items");
if item_lib.check_turn_in(e.trade, {item1 = 13829,item2 = 13829,item3 = 13829,item4 = 13829}) then
total_champagne = total_champagne + 4;
champagne = 4;
elseif item_lib.check_turn_in(e.trade, {item1 = 13829,item2 = 13829,item3 = 13829}) then
total_champagne = total_champagne + 3;
champagne = 3;
elseif item_lib.check_turn_in(e.trade, {item1 = 13829,item2 = 13829}) then
total_champagne = total_champagne + 2;
champagne = 2;
elseif …
```
> [Handin] Fix Lua edge case on stackable hand-in of 4

- zone/client_packet.cpp
Zero expectations as usual.  Feel free to ignore/delete/whatever.
This is mostly a quality of life request.  The main pain point being a bard who uses /melody a lot is when I'm facing a dispelling enemy I'm having to constantly stop and restart the melody to use my instant-class clickies to throw back up my trash buffs.   This causes me to lose my place in the melody and is kinda just tedious overall.  This also fixes a somewhat confusing user experience where clicking an instacast clicky makes the castbar disappear despite not interrupting the spell cast.
Tested on a local akk-stack modified to run the latest code in THJ master branch.
**Test Cases**
- Instacast clickies
- Effect activates
- Clickies with cast time
- Effect activates
- Click with charges
- Charges decrease
- Consumable …
> Enable instant cast clickies during bard songs.

- zone/attack.cpp
- zone/bonuses.cpp
- zone/common.h
https://discord.com/channels/1204418766318862356/1312954376700035072
Although the game visually allows up to 3 bard songs with rune effects to stack (Shield of Songs, Nilipus' March of the Wee, Niv's Harmonic) the player does not benefit from the effect of the stacking runes.
This is due to how the original logic determined which rune was 'active' would then swap in the next eligible rune (usually by buff order) when the current one was removed. Since bard songs do not get removed it would never step to the next one to absorb any damage overflow from the first.
Depending on how the songs were applied this could also reduce overall effectiveness of the runes by prioritizing a weaker bard rune before a stronger one.
_(bonuses.cpp)_
An additional field was added to track the spell-id of the …
> Combine rune effects from active bard songs.

- zone/spell_effects.cpp
Kinda just stumbled across this one and then worked my way backwards on what problems it was causing.
The biggest problem seemed to be that whenever a buff fades it would stop whatever song the bard was singing.  This is easy to overlook because:
1. It didn't matter for beneficial songs
2. Most people are playing detrimental songs in a melody.
3. Buffs don't fade that often on the server.
Other potential bugs related to this (I've not verified these, just best attempt to understand the code):
- False positives/negatives on whether or not the player still had buffs with num_hits remaining.
- Nimbus effects not removing or removing when they shouldn't have.
> Fixed an issue with buff fading stopping active bard songs.

- common/shareddb.cpp
Skips setting item price if the item is no rent
> Skip setting item price for no rent items

- zone/spell_effects.cpp
redirect purify effect pointed at by purify body / purification to max total buff slots instead of it failing to check spell effect > GetMaxTotalSlots as current DB data stops at 20. 
removes any meaningful value from effect 1 in db.
extra ranks with higher spell effect or setting it to 63 there should resolve this for server lifetime alternatively.
a more elaborate fix might do math to quantify beneficial buffs and add that to the count, but given the buff cap of 30 is it meaningfully distinct to just cleanse all of the debuffs instead of a complex function to check 30 slots?
> purify body / purify fix

- common/ruletypes.h
- zone/aa.cpp
- zone/mob.h
- zone/spell_effects.cpp
- zone/spells.cpp
In 'aa.cpp' around line 2593 the logic for 'casting' an AA spell goes down two different possible paths depending on if the player was a bard or not.  However a change made for THJ causes us to always go into the first branch to give everyone the benefit being able to use AAs while casting spells.
As a result, some interactions that worked in base EQEmu stopped happening in THJ because the 'SpellFinished' code path does not end up calling 'TryTriggerOnCastFocusEffect' while the 'CastSpell' code path does.
The most prominent example of this is the Shaman 'Languid Bite' AA which procs off casting a slow ability.  This does not proc off the shaman AA slow ability on THJ even though the two work together in EQEmu.  This forces Shamans to have to waste a gem slot on a slow spell they don't …
> Enable trigger on cast (339) focus effects for AA abilities.

- zone/spells.cpp
https://discord.com/channels/1204418766318862356/1336589227022094377
The new codepath we go into for instant-cast clickies on bards was missing the call to 'GetSpellImpliedTargetID'.
Test Cases
Note: Testing this does not work with GM mode enabled since it bypasses various restrictions on casting on other targets.
- Existing test cases for instant-cast clickies continue to work as expected
- Crown of Hatred - Casts on myself when i have an enemy targeted
- Shield of immaculate - Casts on myself when I have an enemy targeted
> Fix implied targeting on instant-cast clickies for bards.

- zone/client_process.cpp
- zone/mob.h
- zone/zone.cpp
Every time global buffs get fired off, the server gets destroyed and World goes down for upwards of 5+ minutes at a time, this creates issues of not being able to log in, prevents zoning and a myriad of other things from working properly.
This change does the following ~
* **Queuing** Queues and fans out global buffs being applied to players once triggered. 
* **Debounce** Debounces global buffs being applied to players once triggered meaning if 10 global buffs were fired off at once, applying global buffs will likely only occur once instead of 10 times for the entire server.
* **Performance** When we applied global buffs at the zone level, multiple nested loops were occurring, this has been simplified down.
* **Messaging** Gives message as feedback to the player that global buffs are …
> [Fix] Queue Global Buffs and Simplify

- zone/spell_effects.cpp
https://discord.com/channels/1204418766318862356/1337529995085484083
Moves the 'has shielded himself from 517 points of damage.' message to FilterBardSongs if the rune spell_id is a bard song.
Test Cases
-Bard rune with filter set to 'Show' - Message appears
-Bard rune with filter set to 'Hide' - No message
-Normal rune with filter set to 'Show' - Message appears
-Normal rune with filter set to 'Hide' - Message appears
> Move bard rune message to BardSong filter.

- zone/client.cpp
Dopplegangers still use AoEs, changelog specifies they shouldn't. 
Change iterates to next spell in memmed list if aoe-related fields are ! < 1 to include float on aoe_range 0f and to keep consistency for int aoe_max_targets.
Issue likely due to IsDamageSpell(spell) catching spells that may fall under IsAEDurationSpell(), IsAENukeSpell(), IsPBAENukeSpell() IsAERainNukeSpell() without exclusion.
> Remove Doppelganger AoE

- common/ruletypes.h
- zone/spells.cpp
This adds the ability to tune the amount of damage that gets reflected from proc spells.
It adds a new rule (`Custom, ProcReflectPercentage`) which defaults to 50 (50%) that can be used to tune this value.  Currently this value is hardcoded to 0 but with this rule you can tune it to behave however you'd like.
> Enables tuning of reflected spell damage from procs.

- zone/client.cpp
reorders the way we send equipment to doppels to match the way NPCs equip items to avoid cases where we send a range slot item first and have it end up equipped in the primary slot.
Fixes big time doppel complaint
> doppel equip issue

- zone/attack.cpp
Spell effects using SE_NegateAttacks prevent mobs from receiving damage shield damage but are not removed when absorbing damage shield damage.
This means in practice that you can use effects like these to gain permanent immunity to damage shield effects as long as you aren't getting hit otherwise.
These effects should either not prevent damage shield damage or should be removed by receiving damage shield damage.
Fixes # [(issue)](https://discord.com/channels/1204418766318862356/1340807364970020916)
This just expands the existing `if (!from_damage_shield) {` condition so that it skips removing a charge and also skips preventing damage. The current behavior is that it only skips removing a charge.
I think the bug originally was introduced in this commit …
> Prevent `SE_NegateAttacks` from absorbing damage shield damage

- zone/tradeskills.cpp
Tradeskill containers with slots > 10 are treated as custom ones which require SPECIFIC items, less than 10 will do fuzzy item version matching
> Tradeskill fix for fuzzy item matching

- zone/bonuses.cpp
This fixes a bug where Haste v3 effects were all granting over 100% (25% is the configured maximum) v3 haste.
> Fixes Haste V3 calculation

- world/worlddb.cpp
- world/worlddb.h
This is a performance adjustment for **World** where on THJ at 4,000 players and 2,000 zoneservers we observe more of the stress points of world. This cuts down on query volume dramatically.
When you have 12 characters, you can produce well over 100 queries just by hitting character select. The same amount of queries get produced when you delete or create a character while in character select. Most of these queries are from queries inside of a loop. Instead, we bulk load as much as we can at once and only run about 5 queries.
[Example](https://gist.github.com/Akkadius/34e0639c5f27871cee16b0355874d89d) of World queries before when someone would hit character select (Previously)
**Bulk Loading**
* We fetch all character rows at once
* We fetch all databuckets at once
* We fetch all …
> [Performance] Improve Character Select DB Performance

- zone/npc.cpp
I ran into this while leveling a new character -- I found that I could hit "pet back" and then my pet would start getting the 10% ooc regen every tick.
This is also exploitable in combat by setting pet hold + pet back off to force the pet to get ooc regen while being attacked.
> Fixes an issue where pets are able to get OOC regen while still technically in combat

- zone/bonuses.cpp
This fixes a bug where pets were not having the CappedItemBonus rules actually applied because the `CalcCappedItemBonus` function only applies the cap to clients / bots / mercs right now.
With the fix, pets will now also properly be subject to caps
> Applies `CappedItemBonuses` properly to pets

- zone/exp.cpp
Fixes an issue where players who already have more than the AA cap are able to continue to earn more AA than the AA cap.
This just prevents earning more, it doesn't reset them below the cap.
> Fixes extremely complicated AA cap logic issue

- zone/special_attacks.cpp
Fixes this crazy bug where mobs who are eligible for ranged attacks fire arrows like an insane machine gun.
Pictured:
> Prevent ranged attacking mobs from firing machine guns

- zone/loot.cpp
Fixes a bug where NPCs can equip augments in their hands and then can't effectively attack anymore
> Don't allow NPCs to equip augments

- zone/loot.cpp
This fixes a discrepancy where calling the `npc:ClearItemList` quest function would remove items from the NPC's loot table but not from their actual inventory.
With this change, we'll both remove all items from their inventory / equipped items and from their loot table when calling the function.
https://github.com/The-Heroes-Journey-EQEMU/Server/blob/38bebf3de4a4cd5311b85df2c99c0a3cd9d9a6bf/zone/loot.cpp#L846-L885
> Also removes items when clearing loot items

- zone/client.cpp
- zone/client.h
- zone/client_packet.cpp
This generates giant queries during frequent saves and adds needless overhead to zones. This only saves what's changed 
No testing done
> [Performance] Only save changed kill counters

- common/ruletypes.h
- zone/tradeskills.cpp
This PR adds a new RuleR, TradeskillUpMinChance.  By default it is 2.5%.  If you were to set it to, say, 25%, then every tradeskill combine would give you at least a 25% chance to gain a skill point.
Awhile ago during a Q&A, Aporia said something that alluded to the fact that he's adjusted values in the database and set tradeskills to be as easy as possible, but it's not working.  I believe it's because tradeskills have two checks:
- The "stage1" check, which is influenced by whether you passed or failed, your stats, and the specific tradeskill you are doing.
- The "stage2" check, which is a linear percentage that starts at 92% for skill level 15, and drops down to 2.5% at skill level 299.
This is where "TradeskillUpMinChance" comes into play.  By default, it's 2.5 so it will not affect …
> Add Character:TradeskillUpMinChance rule

- zone/attack.cpp
- zone/special_attacks.cpp
Fixes critical strike messages to be accurate, even taking into account the new rule regarding heroic strength and melee attacks.
* Tested Ranged Crits:
* Tested Melee Crits:
* Tested Skill Crits:
* Tested Crippling Blow:
* Tested Cleaving Blow:
* Tested Slay Undead:
Clients tested: THJ Client (5/18/2025)
> Adjust crit message locations
